### ISSUE TITLE
drf_spectacular.views.SpectacularAPIView generated wrong response schema

### ISSUE THREAD

**Issue by retry51776** [tbeadle/django-rest-framework-link-header-pagination#5]
`drf_spectacular.views.SpectacularAPIView` calls `get_paginated_response_schema()` to generate response schema;
It's important because `openapi-client-cli` uses `drf_spectacular` generated schema to generate api-client codes;

https://github.com/encode/django-rest-framework/blob/f3bb5b9cdc7cb53c27535e4817112e6d2eba08a0/rest_framework/pagination.py#L232

We need to override this method; I will open PR soon;

**Comment by retry51776** [comment]
Ahhh, I'm too lazy to fork repo; here is fix to add to LinkHeaderPagination

```
    def get_paginated_response_schema(self, schema):
        return schema
 ```

**Comment by tbeadle** [comment]
Thanks! Fixed in https://github.com/tbeadle/django-rest-framework-link-header-pagination/commit/7a47b8845303897db50cd5ab5fdb22d3ae824c04
