### ISSUE TITLE
Missing pypi release of 0.2.0

### ISSUE THREAD

**Issue by matslindh** [tbeadle/django-rest-framework-link-header-pagination#7]
Would it be possible to get 0.2.0 with the offset pagination released to pypi as well?

**Comment by tbeadle** [comment]
I believe it is already. I just did `pipenv install drf_link_header_pagination==0.2.0` and see it there:

```
└─$ grep '^class' __init__.py
class LinkHeaderMixin:
class LinkHeaderLimitOffsetPagination(LinkHeaderMixin, LimitOffsetPagination):
class LinkHeaderPagination(LinkHeaderMixin, PageNumberPagination):
class LinkHeaderCursorPagination(LinkHeaderMixin, CursorPagination):
class LinkHeaderLinkResponseCursorPagination(LinkHeaderMixin, CursorPagination):
```

**Comment by matslindh** [comment]
It is! That's weird. pypi reported no new relases and just the previous release earlier today. Maybe a stale cache somewhere. Solved now!

**Comment by matslindh** [comment]
OK, I've found the reason for the confusion. The project has two published packages on PyPI, I was looking at the wrong project. So for anyone finding this in the future:

https://pypi.org/project/djangorestframework-link-header-pagination/ (old) vs
https://pypi.org/project/drf-link-header-pagination/ (updated)
